name:                dm-dashboard
version:             0.1.0.0
github:              "michaelmdresser/dm-dashboard"
license:             BSD3
author:              "Michael Dresser"
maintainer:          "michaelmdresser@gmail.com"
copyright:           "2019 Michael M. Dresser"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/michaelmdresser/dm-dashboard#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  dm-dashboard-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dm-dashboard

tests:
  dm-dashboard-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dm-dashboard
